// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

const databaseUrl =
  process.env['DATABASE_URL'] ??
  (() => {
    const host = process.env['DATABASE_HOST'];
    const port = process.env['DATABASE_PORT'] ?? '5432';
    const name = process.env['DATABASE_NAME'];
    const user = process.env['DATABASE_USER'];
    const password = process.env['DATABASE_PASSWORD'];

    if (!host || !name || !user || !password) {
      throw new Error(
        'Missing database configuration. Set DATABASE_URL or DATABASE_HOST, DATABASE_PORT, DATABASE_NAME, DATABASE_USER, and DATABASE_PASSWORD.',
      );
    }

    const encodedUser = encodeURIComponent(user);
    const encodedPassword = encodeURIComponent(password);

    return `postgresql://${encodedUser}:${encodedPassword}@${host}:${port}/${name}`;
  })();

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: databaseUrl,
  },
});
