// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

const databaseUrl = (() => {
  const directUrl = process.env['DATABASE_URL'];
  if (directUrl) return directUrl;

  const host = process.env['DATABASE_HOST'];
  const port = process.env['DATABASE_PORT'] ?? '5432';
  const name = process.env['DATABASE_NAME'];
  const user = process.env['DATABASE_USER'];
  const password = process.env['DATABASE_PASSWORD'];

  if (host && name && user && password) {
    const encodedUser = encodeURIComponent(user);
    const encodedPassword = encodeURIComponent(password);
    return `postgresql://${encodedUser}:${encodedPassword}@${host}:${port}/${name}`;
  }

  // Fallback for build-time commands such as `prisma generate` when DB env vars are unavailable.
  return 'postgresql://postgres:postgres@localhost:5432/postgres';
})();

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: databaseUrl,
  },
});
